"""Metadata for dont_be_lazy. Generated by metametameta — do not edit by hand."""

__all__ = [
    "__credits__",
    "__description__",
    "__keywords__",
    "__license__",
    "__readme__",
    "__requires_python__",
    "__status__",
    "__title__",
    "__version__",
]

__title__ = "dont_be_lazy"
__version__ = "0.1.1"
__description__ = "Tool that finds evidence of past skipped linting"
__readme__ = "README.md"
__credits__ = [{"name": "Matthew Martin", "email": "matthewdeanmartin@gmail.com"}]
__keywords__ = ["dont_be_lazy"]
__license__ = "MIT"
__requires_python__ = ">=3.9"
__status__ = "3 - Alpha"
